// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0llQ-sgiuzVCtjE42BNRu1MjxCAksbQ',
    appId: '1:898201720940:web:31a5edb268a1bc093be049',
    messagingSenderId: '898201720940',
    projectId: 'continuum-fa1c6',
    authDomain: 'continuum-fa1c6.firebaseapp.com',
    storageBucket: 'continuum-fa1c6.firebasestorage.app',
    measurementId: 'G-MFV6J78HF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDathfPSn0nVpaGZQRw5jfUYGmkUTKHHpA',
    appId: '1:898201720940:android:689f63f7283c5d393be049',
    messagingSenderId: '898201720940',
    projectId: 'continuum-fa1c6',
    storageBucket: 'continuum-fa1c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3esHDBLDUfQaqtUmp2-eG24EVT6t2biE',
    appId: '1:898201720940:ios:062e9f7d764b4bda3be049',
    messagingSenderId: '898201720940',
    projectId: 'continuum-fa1c6',
    storageBucket: 'continuum-fa1c6.firebasestorage.app',
    iosBundleId: 'com.example.continuum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3esHDBLDUfQaqtUmp2-eG24EVT6t2biE',
    appId: '1:898201720940:ios:062e9f7d764b4bda3be049',
    messagingSenderId: '898201720940',
    projectId: 'continuum-fa1c6',
    storageBucket: 'continuum-fa1c6.firebasestorage.app',
    iosBundleId: 'com.example.continuum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0llQ-sgiuzVCtjE42BNRu1MjxCAksbQ',
    appId: '1:898201720940:web:2e6341c2c7038fde3be049',
    messagingSenderId: '898201720940',
    projectId: 'continuum-fa1c6',
    authDomain: 'continuum-fa1c6.firebaseapp.com',
    storageBucket: 'continuum-fa1c6.firebasestorage.app',
    measurementId: 'G-8KWXMXC4S1',
  );
}
